export const offerings = [
  { name: 'Meta Ads', icon: 'meta-0045068805.png', color: '#0081FB', tag: 'PAID REACH', description: 'We plan, launch and manage paid campaigns across Meta, testing creative and audiences to help your content reach the right people.', details: ['Campaign strategy', 'Creative testing', 'Audience targeting'], outcome: 'The right content. The right audience.' },
  { name: 'Instagram', icon: 'ig-f930072298.png', color: '#C92BB7', tag: 'BUILD YOUR PRESENCE', description: 'From posts and stories to reels, we plan content, manage publishing and keep your Instagram community engaged.', details: ['Reels & stories', 'Publishing schedules', 'Community management'], outcome: 'A presence that keeps growing.' },
  { name: 'Phone Farm', icon: 'phone-pharm.png', color: '#F0E6FF', tag: 'DISTRIBUTION INFRASTRUCTURE', description: 'Our distribution network supports coordinated publishing across accounts and markets, helping your content reach audiences beyond a single profile.', details: ['Managed devices', 'Multi-country distribution', 'Coordinated publishing'], outcome: 'Beyond one account. Across borders.' },
  { name: 'Snapchat', icon: 'sc-0972fff313.png', color: '#FFFB00', tag: 'STORIES THAT TRAVEL', description: 'We develop stories and discovery content for Snapchat, with a publishing approach built around how people use the platform.', details: ['Story development', 'Discovery content', 'Publishing strategy'], outcome: 'Made for the way people watch.' },
  { name: 'TikTok', icon: 'tiktok-1329cebe69.png', color: '#FFFFFF', tag: 'SHORT FORM. LONG-TERM THINKING.', description: 'We create short-form content, develop repeatable formats and manage publishing to help creators build their presence on TikTok.', details: ['Short-form production', 'Repeatable formats', 'Channel growth'], outcome: 'Turn a moment into momentum.' },
  { name: 'Reddit', icon: 'reddit-412bd214fe.png', color: '#FF4500', tag: 'COMMUNITY FIRST', description: 'We help creators understand relevant communities and participate in conversations with content suited to each community’s rules and interests.', details: ['Community research', 'Relevant content', 'Audience engagement'], outcome: 'Find the conversations that matter.' },
  { name: 'YouTube', icon: 'yt-41e7519772.png', color: '#FF0000', tag: 'BUILD YOUR CHANNEL', description: 'We support video planning, production and publishing, helping creators build a consistent channel across long-form content and Shorts.', details: ['Video planning', 'Long-form & Shorts', 'Channel management'], outcome: 'A channel built for the next chapter.' },
  { name: 'Influencer Collaborations', icon: null, color: '#BCA4FF', tag: 'BETTER TOGETHER', description: 'We connect creators with suitable collaborators and brand partners, coordinating ideas, agreements and delivery from start to finish.', details: ['Creator matching', 'Partnership coordination', 'Campaign delivery'], outcome: 'The right people. More possibilities.' },
];
